Repository Antares-Network/CSSC-Bot, pull requests merged in 2022-09, with the labels that each got.

#12 New Version (2.2.0)
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-image.yml
  .github/workflows/format.yml
  .github/workflows/publish-docker-image.yml
  .prettierignore
  Dockerfile
  LICENSE
  README.md
  commands/owner/createRoles.ts
  commands/owner/csClassPoll.ts
  commands/owner/staffPoll.ts
  commands/owner/yearPoll.ts
  commands/user/clear.ts
  commands/user/github.ts
  commands/user/help.ts
  commands/user/ping.ts
  commands/user/status.ts
  commands/user/version.ts
  commands/user/view.ts
  definitions.ts
  features/interactionCreate.ts
  features/status-changer.ts
  index.ts
  models/classModel.ts
  models/staffModel.ts
  models/yearModel.ts
  package-lock.json
  package.json
  rolesOps.ts
  tsconfig.json
Labels: enhancement, Bug Fix, Version 2.2.0

#14 Update README.md
  README.md
Labels: README

#15 Create dependabot.yml
  .github/dependabot.yml
Labels: Actions, Automation

#19 Nathen418/update dependabot
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/docker-image.yml
  .github/workflows/publish-docker-image.yml
Labels: Bug Fix, Actions, Automation

#24 update what branches workflows to run on correct branches and triggers
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-image.yml
  .github/workflows/format.yml
  .github/workflows/publish-docker-image.yml
Labels: Bug Fix

#25 Add Contributing Standards
  CONTRIBUTING.md
Labels: documentation, README

#26 PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: New Features

#29 Fix bug in `addNewRole`
  rolesOps.ts
Labels: Bug Fix, Version 2.2.x

#28 Bugfix/schiltz3/deepsource
  commands/owner/csClassPoll.ts
  commands/owner/staffPoll.ts
  commands/owner/yearPoll.ts
  commands/user/github.ts
  commands/user/help.ts
  commands/user/ping.ts
  commands/user/status.ts
  commands/user/uptime.ts
  commands/user/version.ts
  features/status-changer.ts
  features/statuspage.ts
  index.ts
  rolesOps.ts
  util.ts
Labels: Rewrite, Bug Fix, Version 2.2.x

#27 Minor version update | 2.2.0 --> 2.2.1
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-image.yml
  .github/workflows/format.yml
  .github/workflows/publish-docker-image.yml
  .gitignore
  CONTRIBUTING.md
  commands/owner/createRoles.ts
  commands/owner/csClassPoll.ts
  commands/owner/staffPoll.ts
  commands/owner/yearPoll.ts
  commands/user/clear.ts
  commands/user/github.ts
  commands/user/help.ts
  commands/user/ping.ts
  commands/user/status.ts
  commands/user/uptime.ts
  commands/user/version.ts
  features/interactionCreate.ts
  features/status-changer.ts
  features/statuspage.ts
  index.ts
  models/classModel.ts
  models/staffModel.ts
  models/yearModel.ts
  package-lock.json
  package.json
  rolesOps.ts
  util.ts
Labels: Rewrite, Bug Fix, Version 2.2.x, Actions, Bug Risk

#30 Bugfix/nathen418/update docker publish
  .github/workflows/publish-docker-image.yml
Labels: Bug Fix, Actions, Automation

#32 Merge fix from #30 into Main
  .github/workflows/publish-docker-image.yml
Labels: Bug Fix, Actions, Automation

#36 Feature/schiltz3/move utils
  commands/owner/createRoles.ts
  commands/owner/csClassPoll.ts
  commands/owner/staffPoll.ts
  commands/owner/yearPoll.ts
  commands/user/clear.ts
  commands/user/view.ts
  features/interactionCreate.ts
  models/classModel.ts
  models/staffModel.ts
  models/yearModel.ts
  utils/roleUtils.ts
  utils/util.ts
Labels: Rewrite

#37 Feature/nathen418/detect containerization
  env.template
  features/statuspage.ts
  index.ts
  package-lock.json
  package.json
  utils/util.ts
Labels: New Features

#39 Feature/schiltz3/create channels
  commands/owner/csCreateChannels.ts
  utils/channelUtils.ts
Labels: Version 2.2.x, New Features, Requires Careful Review

#46 Replace string concatenation with template
  commands/user/view.ts
Labels: Bug Fix
