Repository Antares-Network/CSSC-Bot, pull requests merged in 2022-08, with the labels that each got.

#1 Rewrite of CSSC-bot in Typescript using Discord.js and WOKCommands (Part 1-5)
  .gitignore
  README.md
  TODO.md
  commands/owner/staffPoll.ts
  commands/owner/yearPoll.ts
  commands/user/clearRoles.ts
  commands/user/github.ts
  commands/user/help.ts
  commands/user/status.ts
  commands/user/uptime.ts
  commands/user/viewRoles.ts
  definitions.ts
  env.template
  features/interactionCreate.ts
  features/status-changer.ts
  features/statuspage.ts
  img/botface.jpg
  index.ts
  json/msg_ids.json
  logs/bot.txt
  logs/discord.txt
  logs/server.txt
  modules/logger.py
  modules/persistance.py
  modules/role_poll.py
  modules/utils.py
  package-lock.json
  package.json
  rolebot.py
  rolesOps.ts
  tkn.py
  tsconfig.json
  txt/cmds.txt
Labels: Rewrite

#2 Rewrite of CSSC-bot in Typescript using Discord.js and WOKCommands (Pr2)
  .gitignore
  Dockerfile
  README.md
  TODO.md
  commands/owner/createRoles.ts
  commands/owner/say.ts
  commands/owner/staffPoll.ts
  commands/owner/yearPoll.ts
  commands/user/clearRoles.ts
  commands/user/github.ts
  commands/user/help.ts
  commands/user/ping.ts
  commands/user/status.ts
  commands/user/uptime.ts
  commands/user/version.ts
  commands/user/viewRoles.ts
  definitions.ts
  demo/college-staff-poll.png
  demo/college-year-poll.png
  env.template
  features/interactionCreate.ts
  features/status-changer.ts
  features/statuspage.ts
  img/botface.jpg
  index.ts
  json/msg_ids.json
  logs/bot.txt
  logs/discord.txt
  logs/server.txt
  modules/logger.py
  modules/persistance.py
  modules/role_poll.py
  modules/utils.py
  package-lock.json
  package.json
  rolebot.py
  rolesOps.ts
  tkn.py
  tsconfig.json
  txt/cmds.txt
Labels: Rewrite, Version 2.1.0

#7 Add prettier ci and script
  .github/workflows/format.yml
  .prettierignore
  commands/owner/createRoles.ts
  commands/owner/say.ts
  commands/owner/staffPoll.ts
  commands/owner/yearPoll.ts
  commands/user/clearRoles.ts
  commands/user/github.ts
  commands/user/help.ts
  commands/user/ping.ts
  commands/user/status.ts
  commands/user/uptime.ts
  commands/user/version.ts
  commands/user/viewRoles.ts
  definitions.ts
  features/interactionCreate.ts
  features/status-changer.ts
  features/statuspage.ts
  index.ts
  package-lock.json
  package.json
  rolesOps.ts
Labels: enhancement
