Repository Antares-Network/CSSC-Bot, pull requests merged in 2023-01, with the labels that each got.

#92 Feature/schiltz3/testing
  __tests__/utils/channels.tests.ts
  jest.config.js
  package-lock.json
  package.json
Labels: New Features

#88 Bugfix/schiltz3/deepsource
  __tests__/utils/channels.tests.ts
  commands/owner/createRoles.ts
  commands/owner/csCreateChannels.ts
  index.ts
  utils/channels.ts
  utils/roles.ts
Labels: Bug Risk

#94 Bugfix/schiltz3/deepsource2
  commands/owner/csCreateChannels.ts
  index.ts
  utils/channels.ts
Labels: Bug Fix

#93 Prevent error when statuspage env vars are not set
  features/statuspage.ts
Labels: Bug Fix

#48 Feature/schiltz3/db migrate
  .gitignore
  README.md
  __tests__/utils/channels.tests.ts
  __tests__/utils/roles.tests.ts
  package-lock.json
  package.json
  src/commands/owner/csClassPoll.ts
  src/commands/owner/csCreateChannels.ts
  src/commands/owner/migrateDB.ts
  src/commands/owner/staffPoll.ts
  src/commands/owner/yearPoll.ts
  src/commands/user/github.ts
  src/commands/user/help.ts
  src/commands/user/ping.ts
  src/commands/user/status.ts
  src/commands/user/uptime.ts
  src/commands/user/version.ts
  src/features/interactionCreate.ts
  src/features/status-changer.ts
  src/models/classModel.ts
  src/utils/channels.ts
  src/utils/embeds.ts
  src/utils/roles.ts
Labels: Rewrite, Bug Fix, Version 2.2.x

#103 use === instead of ==
  src/commands/owner/csClassPoll.ts
  src/commands/owner/csCreateChannels.ts
Labels: Bug Risk

#108 check against roles not channels
  src/utils/roles.ts
Labels: Bug Fix

#107 Report name of matching channel not id
  src/commands/owner/csCreateChannels.ts
Labels: Bug Fix
